title: Core Detailing Solutions
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Website advertising Core Detailing solutions
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: assets/css